In [2]:
import yfinance as yf
import pandas as pd
import os

In [3]:
if os.path.exists("sp500.csv"):
    sp500 = pd.read_csv("sp500.csv", index_col=0)
else:
    sp500 = yf.Ticker("^GSPC")
    sp500 = sp500.history(period="max")
    sp500.to_csv("sp500.csv")

In [4]:
sp500.index = pd.to_datetime(sp500.index)

In [5]:
sp500

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1927-12-30 00:00:00-05:00,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
1928-01-03 00:00:00-05:00,17.760000,17.760000,17.760000,17.760000,0,0.0,0.0
1928-01-04 00:00:00-05:00,17.719999,17.719999,17.719999,17.719999,0,0.0,0.0
1928-01-05 00:00:00-05:00,17.549999,17.549999,17.549999,17.549999,0,0.0,0.0
1928-01-06 00:00:00-05:00,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
...,...,...,...,...,...,...,...
2023-10-03 00:00:00-04:00,4269.750000,4281.149902,4216.450195,4229.450195,3953830000,0.0,0.0
2023-10-04 00:00:00-04:00,4233.830078,4268.500000,4220.479980,4263.750000,3777600000,0.0,0.0
2023-10-05 00:00:00-04:00,4259.310059,4267.129883,4225.910156,4258.189941,3581470000,0.0,0.0
2023-10-06 00:00:00-04:00,4234.790039,4324.100098,4219.549805,4308.500000,3902030000,0.0,0.0
2023-10-09 00:00:00-04:00,4289.020020,4341.729980,4283.790039,4335.660156,3174630000,0.0,0.0